//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fase2.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/datos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable datos(string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/datos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> datosAsync(string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Consulta1(string tabla, string columna, string valor, string get);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta1", ReplyAction="*")]
        System.Threading.Tasks.Task<string> Consulta1Async(string tabla, string columna, string valor, string get);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Login(string usuario, string contraseña, string Rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LoginAsync(string usuario, string contraseña, string Rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update(string tabla, string columna, string valor, string restriccion1, string restriccion2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string tabla, string columna, string valor, string restriccion1, string restriccion2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ingresar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Ingresar(string Tabla, string columnas, string valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ingresar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IngresarAsync(string Tabla, string columnas, string valores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectarServidor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool conectarServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/conectarServidor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> conectarServidorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] Consulta(string tablas, string columnas, string llaves, string get);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<object[]> ConsultaAsync(string tablas, string columnas, string llaves, string get);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Fase2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Fase2.ServiceReference1.WebService1Soap>, Fase2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable datos(string valor) {
            return base.Channel.datos(valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> datosAsync(string valor) {
            return base.Channel.datosAsync(valor);
        }
        
        public string Consulta1(string tabla, string columna, string valor, string get) {
            return base.Channel.Consulta1(tabla, columna, valor, get);
        }
        
        public System.Threading.Tasks.Task<string> Consulta1Async(string tabla, string columna, string valor, string get) {
            return base.Channel.Consulta1Async(tabla, columna, valor, get);
        }
        
        public int Login(string usuario, string contraseña, string Rol) {
            return base.Channel.Login(usuario, contraseña, Rol);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string usuario, string contraseña, string Rol) {
            return base.Channel.LoginAsync(usuario, contraseña, Rol);
        }
        
        public bool Update(string tabla, string columna, string valor, string restriccion1, string restriccion2) {
            return base.Channel.Update(tabla, columna, valor, restriccion1, restriccion2);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string tabla, string columna, string valor, string restriccion1, string restriccion2) {
            return base.Channel.UpdateAsync(tabla, columna, valor, restriccion1, restriccion2);
        }
        
        public bool Ingresar(string Tabla, string columnas, string valores) {
            return base.Channel.Ingresar(Tabla, columnas, valores);
        }
        
        public System.Threading.Tasks.Task<bool> IngresarAsync(string Tabla, string columnas, string valores) {
            return base.Channel.IngresarAsync(Tabla, columnas, valores);
        }
        
        public bool conectarServidor() {
            return base.Channel.conectarServidor();
        }
        
        public System.Threading.Tasks.Task<bool> conectarServidorAsync() {
            return base.Channel.conectarServidorAsync();
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public object[] Consulta(string tablas, string columnas, string llaves, string get) {
            return base.Channel.Consulta(tablas, columnas, llaves, get);
        }
        
        public System.Threading.Tasks.Task<object[]> ConsultaAsync(string tablas, string columnas, string llaves, string get) {
            return base.Channel.ConsultaAsync(tablas, columnas, llaves, get);
        }
    }
}
